#!/usr/bin/env python3
"""
Offline RL training (Variant A conservative offline actor-critic).

This script is intentionally dependency-light: it uses only PyTorch + numpy.
Training procedure:
  1) Behavior Cloning (BC) warm-start for the actor.
  2) Conservative critic updates + BC-regularized actor updates.

Input: dataset generated by `models/rl/generate_dataset.py` (.npz + .meta.json)
Output: torch artifact (.pt) consumable by `RlPolicyController`.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


def _set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


class MLP(nn.Module):
    def __init__(self, *, in_dim: int, out_dim: int, hidden_dims: list[int], act: str = "relu") -> None:
        super().__init__()
        layers: list[nn.Module] = []
        prev = in_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev, h))
            if act == "relu":
                layers.append(nn.ReLU())
            elif act == "gelu":
                layers.append(nn.GELU())
            else:
                raise ValueError(f"Unsupported act: {act}")
            prev = h
        layers.append(nn.Linear(prev, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class Actor(nn.Module):
    def __init__(self, *, obs_dim: int, hidden_dims: list[int], setpoint_min: float, setpoint_max: float) -> None:
        super().__init__()
        self.setpoint_min = float(setpoint_min)
        self.setpoint_max = float(setpoint_max)

        # Output in normalized range [-1, 1] for both components.
        self.body = MLP(in_dim=obs_dim, out_dim=2, hidden_dims=hidden_dims, act="relu")

    def forward(self, obs_norm: torch.Tensor) -> torch.Tensor:
        # tanh keeps within [-1, 1] without hard clipping.
        return torch.tanh(self.body(obs_norm))

    def to_action(self, actor_out_norm: torch.Tensor) -> torch.Tensor:
        """
        Convert actor output in [-1,1] to absolute action:
          - setpoint in [setpoint_min, setpoint_max]
          - fan_speed_pct in [0,100]
        """
        # actor_out_norm[:, 0] -> setpoint_norm in [-1,1]
        setpoint_norm = actor_out_norm[:, 0]
        fan_norm = actor_out_norm[:, 1]

        setpoint = self.setpoint_min + (setpoint_norm + 1.0) * 0.5 * (self.setpoint_max - self.setpoint_min)
        fan_speed = (fan_norm + 1.0) * 0.5 * 100.0
        return torch.stack([setpoint, fan_speed], dim=1)

    @staticmethod
    def norm_action_to_absolute(
        actor_out_norm: torch.Tensor,
        *,
        setpoint_min: float,
        setpoint_max: float,
    ) -> torch.Tensor:
        setpoint_norm = actor_out_norm[:, 0]
        fan_norm = actor_out_norm[:, 1]
        setpoint = setpoint_min + (setpoint_norm + 1.0) * 0.5 * (setpoint_max - setpoint_min)
        fan_speed = (fan_norm + 1.0) * 0.5 * 100.0
        return torch.stack([setpoint, fan_speed], dim=1)


class Critic(nn.Module):
    def __init__(self, *, obs_dim: int, action_norm_dim: int = 2, hidden_dims: list[int]) -> None:
        super().__init__()
        self.q = MLP(in_dim=obs_dim + action_norm_dim, out_dim=1, hidden_dims=hidden_dims, act="relu")

    def forward(self, obs_norm: torch.Tensor, action_norm: torch.Tensor) -> torch.Tensor:
        x = torch.cat([obs_norm, action_norm], dim=1)
        return self.q(x).squeeze(-1)  # [B]


@dataclass(frozen=True)
class TrainingConfig:
    device: str
    gamma: float
    batch_size: int
    updates: int
    bc_pretrain_updates: int
    bc_lambda: float
    critic_lr: float
    actor_lr: float
    target_tau: float
    cql_alpha: float
    cql_temp: float
    cql_num_random_actions: int
    obs_std_eps: float


def _action_to_norm(
    actions_abs: torch.Tensor,
    *,
    setpoint_min: float,
    setpoint_max: float,
) -> torch.Tensor:
    """
    Map absolute actions to normalized [-1,1]:
      setpoint in [setpoint_min, setpoint_max]
      fan_speed_pct in [0,100]
    """
    setpoint = actions_abs[:, 0]
    fan = actions_abs[:, 1]

    setpoint_norm = 2.0 * (setpoint - setpoint_min) / (setpoint_max - setpoint_min) - 1.0
    fan_norm = 2.0 * fan / 100.0 - 1.0
    return torch.stack([setpoint_norm, fan_norm], dim=1)


def train_offline(
    *,
    dataset_path: Path,
    out_path: Path,
    seed: int,
    config: TrainingConfig,
    actor_hidden: list[int],
    critic_hidden: list[int],
) -> None:
    if not dataset_path.exists():
        raise FileNotFoundError(dataset_path)

    meta_path = dataset_path.with_suffix(".meta.json")
    if not meta_path.exists():
        raise FileNotFoundError(f"Missing dataset meta: {meta_path}")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))

    data = np.load(dataset_path)
    obs = data["obs"].astype(np.float32)  # [N, D]
    actions = data["actions"].astype(np.float32)  # [N, 2]
    rewards = data["rewards"].astype(np.float32)  # [N]
    next_obs = data["next_obs"].astype(np.float32)  # [N, D]
    dones = data["dones"].astype(np.bool_)  # [N]

    obs_dim = int(obs.shape[1])
    N = int(obs.shape[0])
    if N < config.batch_size:
        raise RuntimeError(f"Dataset too small: N={N}, batch={config.batch_size}")

    obs_mean = obs.mean(axis=0, keepdims=True)
    obs_std = obs.std(axis=0, keepdims=True) + float(config.obs_std_eps)

    # Normalize observations.
    obs_norm = (obs - obs_mean) / obs_std
    next_obs_norm = (next_obs - obs_mean) / obs_std

    setpoint_min = float(meta["constraints"]["setpoint_min"])
    setpoint_max = float(meta["constraints"]["setpoint_max"])

    # Normalize actions for critic/actor output spaces.
    actions_t = torch.tensor(actions, dtype=torch.float32)
    action_norm_t = _action_to_norm(actions_t, setpoint_min=setpoint_min, setpoint_max=setpoint_max)

    rewards_t = torch.tensor(rewards, dtype=torch.float32)
    dones_t = torch.tensor(dones.astype(np.float32), dtype=torch.float32)  # 1.0 if done else 0.0

    obs_norm_t = torch.tensor(obs_norm, dtype=torch.float32)
    next_obs_norm_t = torch.tensor(next_obs_norm, dtype=torch.float32)

    device = torch.device(config.device)
    obs_norm_t = obs_norm_t.to(device)
    next_obs_norm_t = next_obs_norm_t.to(device)
    action_norm_t = action_norm_t.to(device)
    rewards_t = rewards_t.to(device)
    dones_t = dones_t.to(device)

    actor = Actor(obs_dim=obs_dim, hidden_dims=actor_hidden, setpoint_min=setpoint_min, setpoint_max=setpoint_max).to(device)
    critic1 = Critic(obs_dim=obs_dim, hidden_dims=critic_hidden).to(device)
    critic2 = Critic(obs_dim=obs_dim, hidden_dims=critic_hidden).to(device)

    actor_tgt = Actor(obs_dim=obs_dim, hidden_dims=actor_hidden, setpoint_min=setpoint_min, setpoint_max=setpoint_max).to(device)
    critic1_tgt = Critic(obs_dim=obs_dim, hidden_dims=critic_hidden).to(device)
    critic2_tgt = Critic(obs_dim=obs_dim, hidden_dims=critic_hidden).to(device)

    actor_tgt.load_state_dict(actor.state_dict())
    critic1_tgt.load_state_dict(critic1.state_dict())
    critic2_tgt.load_state_dict(critic2.state_dict())

    actor_optim = torch.optim.Adam(actor.parameters(), lr=float(config.actor_lr))
    critic_optim = torch.optim.Adam(list(critic1.parameters()) + list(critic2.parameters()), lr=float(config.critic_lr))

    rng = np.random.default_rng(seed)

    def sample_batch() -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        idx = rng.integers(0, N, size=config.batch_size, endpoint=False)
        idx_t = torch.tensor(idx, dtype=torch.long, device=device)
        return (
            obs_norm_t[idx_t],
            action_norm_t[idx_t],
            next_obs_norm_t[idx_t],
            rewards_t[idx_t],
            dones_t[idx_t],
        )

    # --- 1) BC pretrain ---
    actor.train()
    critic1.train()
    critic2.train()
    for step in range(config.bc_pretrain_updates):
        obs_b, action_norm_b, _next_obs_b, _rewards_b, _dones_b = sample_batch()

        pred_action_norm = actor(obs_b)
        bc_loss = F.mse_loss(pred_action_norm, action_norm_b)

        actor_optim.zero_grad(set_to_none=True)
        bc_loss.backward()
        actor_optim.step()

        if (step + 1) % max(1, config.bc_pretrain_updates // 5) == 0:
            print(f"[BC pretrain] step={step+1}/{config.bc_pretrain_updates} bc_loss={bc_loss.item():.6f}")

    # --- 2) Conservative offline actor-critic ---
    actor.train()
    critic1.train()
    critic2.train()

    for step in range(config.updates):
        obs_b, action_norm_b, next_obs_b, reward_b, done_b = sample_batch()

        # Critic target.
        with torch.no_grad():
            next_action_norm = actor_tgt(next_obs_b)
            q1_next = critic1_tgt(next_obs_b, next_action_norm)
            q2_next = critic2_tgt(next_obs_b, next_action_norm)
            q_next = torch.min(q1_next, q2_next)
            target_q = reward_b + float(config.gamma) * (1.0 - done_b) * q_next

        q1 = critic1(obs_b, action_norm_b)
        q2 = critic2(obs_b, action_norm_b)

        mse1 = F.mse_loss(q1, target_q)
        mse2 = F.mse_loss(q2, target_q)

        # Conservative penalty (CQL-like) using random actions.
        # For each state in the batch we sample `K` random actions.
        K = int(config.cql_num_random_actions)
        # Random normalized actions uniform in [-1,1] for both dims.
        # (Which corresponds to uniform in the original action ranges.)
        rand_actions_norm = torch.empty((obs_b.shape[0], K, 2), device=device).uniform_(-1.0, 1.0)
        obs_rep = obs_b.unsqueeze(1).expand(-1, K, -1).reshape(-1, obs_b.shape[1])
        rand_actions_flat = rand_actions_norm.reshape(-1, 2)

        q1_rand = critic1(obs_rep, rand_actions_flat).reshape(obs_b.shape[0], K)
        q2_rand = critic2(obs_rep, rand_actions_flat).reshape(obs_b.shape[0], K)

        # logsumexp penalty: encourages low Q on out-of-distribution actions.
        # This isn't a perfect CQL implementation variant-wise, but works as a conservative regularizer.
        cql_temp = float(config.cql_temp)
        logsumexp_q1 = torch.logsumexp(q1_rand / cql_temp, dim=1) * cql_temp
        logsumexp_q2 = torch.logsumexp(q2_rand / cql_temp, dim=1) * cql_temp
        cql_q1 = logsumexp_q1.mean() - q1.mean()
        cql_q2 = logsumexp_q2.mean() - q2.mean()

        cql_loss = float(config.cql_alpha) * (cql_q1 + cql_q2)

        critic_loss = mse1 + mse2 + cql_loss

        critic_optim.zero_grad(set_to_none=True)
        critic_loss.backward()
        critic_optim.step()

        # Actor update: maximize Q but keep close to dataset action (TD3+BC-style).
        actor_action_norm = actor(obs_b)
        q1_actor = critic1(obs_b, actor_action_norm)
        actor_loss_q = -q1_actor.mean()
        actor_loss_bc = F.mse_loss(actor_action_norm, action_norm_b)
        actor_loss = actor_loss_q + float(config.bc_lambda) * actor_loss_bc

        actor_optim.zero_grad(set_to_none=True)
        actor_loss.backward()
        actor_optim.step()

        # Soft target updates.
        with torch.no_grad():
            for p, p_tgt in zip(actor.parameters(), actor_tgt.parameters()):
                p_tgt.data.mul_(1.0 - float(config.target_tau)).add_(float(config.target_tau) * p.data)
            for p, p_tgt in zip(critic1.parameters(), critic1_tgt.parameters()):
                p_tgt.data.mul_(1.0 - float(config.target_tau)).add_(float(config.target_tau) * p.data)
            for p, p_tgt in zip(critic2.parameters(), critic2_tgt.parameters()):
                p_tgt.data.mul_(1.0 - float(config.target_tau)).add_(float(config.target_tau) * p.data)

        if (step + 1) % max(1, config.updates // 5) == 0:
            print(
                f"[offline] step={step+1}/{config.updates} critic_loss={critic_loss.item():.4f} "
                f"actor_loss={actor_loss.item():.4f} mse1={mse1.item():.4f} cql_loss={cql_loss.item():.4f}"
            )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    policy = {
        "version": "offline_conservative_td3bc_v1",
        "obs_keys": meta.get("obs_keys", None),
        "obs_mean": obs_mean.astype(np.float32),
        "obs_std": obs_std.astype(np.float32),
        "setpoint_min": setpoint_min,
        "setpoint_max": setpoint_max,
        "actor_state_dict": actor.state_dict(),
        "actor_hidden": actor_hidden,
        "critic_hidden": critic_hidden,
        "training": {
            "seed": seed,
            "gamma": config.gamma,
            "batch_size": config.batch_size,
            "updates": config.updates,
            "bc_pretrain_updates": config.bc_pretrain_updates,
            "bc_lambda": config.bc_lambda,
            "cql_alpha": config.cql_alpha,
            "cql_temp": config.cql_temp,
            "cql_num_random_actions": config.cql_num_random_actions,
        },
    }
    torch.save(policy, out_path)
    print(f"Saved policy artifact: {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Offline RL training (conservative actor-critic).")
    parser.add_argument("--dataset-path", type=str, required=True, help="Path to .npz generated dataset")
    parser.add_argument("--out-path", type=str, required=True, help="Output .pt policy path")
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--device", type=str, default="cpu")

    parser.add_argument("--gamma", type=float, default=0.99)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--updates", type=int, default=5000)
    parser.add_argument("--bc-pretrain-updates", type=int, default=2000)
    parser.add_argument("--bc-lambda", type=float, default=1.0)

    parser.add_argument("--actor-lr", type=float, default=1e-4)
    parser.add_argument("--critic-lr", type=float, default=1e-3)
    parser.add_argument("--target-tau", type=float, default=0.005)

    parser.add_argument("--cql-alpha", type=float, default=0.1)
    parser.add_argument("--cql-temp", type=float, default=1.0)
    parser.add_argument("--cql-num-random-actions", type=int, default=10)

    parser.add_argument("--obs-std-eps", type=float, default=1e-6)

    parser.add_argument("--actor-hidden", type=str, default="256,256")
    parser.add_argument("--critic-hidden", type=str, default="256,256")

    args = parser.parse_args()

    actor_hidden = [int(x.strip()) for x in args.actor_hidden.split(",") if x.strip()]
    critic_hidden = [int(x.strip()) for x in args.critic_hidden.split(",") if x.strip()]

    _set_seed(args.seed)

    config = TrainingConfig(
        device=args.device,
        gamma=args.gamma,
        batch_size=args.batch_size,
        updates=args.updates,
        bc_pretrain_updates=args.bc_pretrain_updates,
        bc_lambda=args.bc_lambda,
        actor_lr=args.actor_lr,
        critic_lr=args.critic_lr,
        target_tau=args.target_tau,
        cql_alpha=args.cql_alpha,
        cql_temp=args.cql_temp,
        cql_num_random_actions=args.cql_num_random_actions,
        obs_std_eps=args.obs_std_eps,
    )

    train_offline(
        dataset_path=Path(args.dataset_path),
        out_path=Path(args.out_path),
        seed=args.seed,
        config=config,
        actor_hidden=actor_hidden,
        critic_hidden=critic_hidden,
    )


if __name__ == "__main__":
    main()

